
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author User
 */
import java.awt.*;
import javax.swing.*;
import javafx.embed.swing.JFXPanel;
import java.util.*;
import javafx.application.*;
import javafx.stage.*;
import javafx.scene.*;
import javafx.scene.shape.*;
import javafx.scene.paint.*;

class logoDisplay {

    public static logoDisplay logo;
    public static Renderer2 renderer;
    public static int Width = homescreen.gameLogo.getWidth();
    public static int Height = homescreen.gameLogo.getHeight();
    public static Graphics graphics;
    public static java.awt.Color background = new java.awt.Color(31, 32, 37);

    public static int count = 0;

    public logoDisplay() {
        //creates internal frame to display logo
        JInternalFrame display = new JInternalFrame();

        renderer = new Renderer2();

        display.add(renderer);
        display.setSize(Width, Height);

        display.setResizable(false);
        display.setVisible(true);

        homescreen.gameLogo.add(display); //adds internal frame to panel

    }

    public void repaint(Graphics g) {
        g = logo(1, g);
        if (g instanceof Graphics2D) {
            //text for title of game
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(java.awt.Color.WHITE);
            g2.setFont(new Font("TimesRoman", Font.PLAIN, 36));
            g2.drawString("Snake Game", 220, 135);
        }

    }

    public Graphics logo(double size, Graphics g) {
        //recursive method to draw rectangles for logo
        double width = Width * size;
        double height = Height * size;
        if (count % 2 == 0) {
            g.setColor(background);
        } else {
            g.setColor(java.awt.Color.GREEN.darker().darker());
        }
        g.fillRect((int) ((Width - width) / 2), (int) ((Height - height) / 2), (int) width, (int) height - 30);
        count++;
        if (size > 0.5) {
            logo(size - 0.1, g);
        }
        return g;
    }

}

public class homescreen extends javax.swing.JFrame {

    Group root = new Group();
    public static boolean gameRunning = false;

    /**
     * Creates new form homescreen
     */
    public homescreen() {
        initComponents();

        //makes homescreen invisible and run button visible
        if (!gameRunning) {
            runGame.setVisible(true);
            runGame.setLocation((int) runGame.getBounds().getX() + 350, (int) runGame.getBounds().getY() + 350);
            lbButton.setVisible(false);
            this.setResizable(false);
            rulesButton.setVisible(false);
            playGame.setVisible(false);
        } else {
            lbButton.setVisible(true);
            rulesButton.setVisible(true);
            playGame.setVisible(true);
            runGame.setVisible(false); //hides run button
            gameRunning = true; //indicates that the game is running
            //displays logo
            logoDisplay.logo = new logoDisplay();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        playGame = new javax.swing.JButton();
        rulesButton = new javax.swing.JButton();
        lbButton = new javax.swing.JButton();
        gameLogo = new javax.swing.JPanel();
        runGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        playGame.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        playGame.setText("Play Game");
        playGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameActionPerformed(evt);
            }
        });

        rulesButton.setFont(new java.awt.Font("Tahoma", 0, 42)); // NOI18N
        rulesButton.setText("How to Play");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });

        lbButton.setFont(new java.awt.Font("Tahoma", 0, 40)); // NOI18N
        lbButton.setText("Leaderboard");
        lbButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbButtonActionPerformed(evt);
            }
        });

        gameLogo.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout gameLogoLayout = new javax.swing.GroupLayout(gameLogo);
        gameLogo.setLayout(gameLogoLayout);
        gameLogoLayout.setHorizontalGroup(
            gameLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        gameLogoLayout.setVerticalGroup(
            gameLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );

        runGame.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        runGame.setText("Run Game");
        runGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runGameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbButton)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(runGame, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(playGame))
                            .addComponent(rulesButton))
                        .addGap(194, 194, 194))
                    .addComponent(gameLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gameLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(playGame))
                    .addComponent(runGame, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(rulesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lbButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void playGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameActionPerformed
        // TODO add your handling code here:
        //switch screens to play game
        logoDisplay.renderer.removeAll();
        logoDisplay.count = 0;
        playerName screen = new playerName();
        screen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_playGameActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        // TODO add your handling code here:
        //switch screens to rules
        rules screen = new rules();
        screen.setVisible(true);
        this.setVisible(false);
        logoDisplay.renderer.removeAll();
        logoDisplay.count = 0;
    }//GEN-LAST:event_rulesButtonActionPerformed

    private void lbButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbButtonActionPerformed
        // TODO add your handling code here:
        //switch screens to leaderboard
        logoDisplay.renderer.removeAll();
        logoDisplay.count = 0;
        
        leaderboard screen = new leaderboard();
        screen.setVisible(true);
        this.setVisible(false);
        culminating.addScore(playerName.name, gameDisplay.count);

        //displays score of player
        leaderboard.lbDisplay.setText(culminating.printScore());
        leaderboard.lbDisplay.setEditable(false);
    }//GEN-LAST:event_lbButtonActionPerformed

    private void runGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runGameActionPerformed
        // TODO add your handling code here:
        //makes the homescreen visible
        lbButton.setVisible(true);
        rulesButton.setVisible(true);
        playGame.setVisible(true);
        runGame.setVisible(false); //hides run button
        gameRunning = true; //indicates that the game is running
        //displays logo
        logoDisplay.logo = new logoDisplay();
    }//GEN-LAST:event_runGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homescreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homescreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel gameLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lbButton;
    private javax.swing.JButton playGame;
    private javax.swing.JButton rulesButton;
    private javax.swing.JButton runGame;
    // End of variables declaration//GEN-END:variables
}
